class SenseModuleEvents:
    # Input pin to terminal mapping
    # schematic can be found here:<TBD>
    
    IN_NONE    = 0b0000000000000000
    IN_TP64    = 0b0000000000000001
    IN_TP63    = 0b0000000000000010
    IN_TP62    = 0b0000000000000100
    IN_PEK_ALT = 0b0000000000001000
    IN_EXT4    = 0b0000000000010000
    IN_EXT3    = 0b0000000000100000
    IN_EXT2    = 0b0000000001000000
    IN_EXT1    = 0b0000000010000000
    IN_G       = 0b0000000100000000
    IN_Y1      = 0b0000001000000000
    IN_W1      = 0b0000010000000000
    IN_Y2      = 0b0000100000000000
    IN_W2      = 0b0001000000000000
    IN_OB      = 0b0010000000000000
    IN_ACC     = 0b0100000000000000
    IN_PEK     = 0b1000000000000000
    IN_G2      = IN_Y2 # G2 (medium speed fan) can be configured on the Y2 terminal for supporting devices
    IN_G3      = IN_W2 # G3 (high speed fan) can be configured on the W2 terminal for supporting devices
    IN_OB_ART  = IN_W2 # Only for Artemis W2 and O/B share the same terminal
    IN_G3_ART  = IN_PEK_ALT # Only for Artemis G3 shares PEK+ terminal
    IN_ACC_ART = IN_PEK_ALT # Only for Artemis Acc+ is linked to PEK+ terminal
    
    # Possible events to be detected/verified
    # BO = BOILER,  BF = BOILER W/FAN, FN = FURNACE, HP = HEAT PUMP
    # AUX = AUXILIARY FURNACE, CA = CARRIER/BRYANT

    EVENT_NONE = IN_NONE
    EVENT_HP_NONE = IN_OB

    EVENT_FAN = IN_G
    EVENT_FAN2 = IN_G | IN_G2
    EVENT_FAN3 = IN_G | IN_G2 | IN_G3

    EVENT_ACC_ON = IN_G | IN_ACC
    EVENT_HP_FAN = IN_G | IN_OB
    EVENT_HP_FAN_ACC = IN_G | IN_OB | IN_ACC

    EVENT_BOHEAT_STAGE_1 = IN_W1
    EVENT_BOHEAT_STAGE_2 = IN_W1 | IN_W2

    EVENT_BOHEAT_STAGE_1_ACC = IN_W1 | IN_G | IN_ACC
    EVENT_BOHEAT_STAGE_2_ACC = IN_W1 | IN_W2 | IN_G | IN_ACC

    EVENT_BFHEAT_STAGE_1 = IN_G | IN_W1
    EVENT_BFHEAT_STAGE_2 = IN_G | IN_W1 | IN_W2

    EVENT_BFHEAT_STAGE_1_ACC = IN_G | IN_W1 | IN_ACC
    EVENT_BFHEAT_STAGE_2_ACC = IN_G | IN_W1 | IN_W2 | IN_ACC

    EVENT_FNHEAT_STAGE_1 = IN_G | IN_W1
    EVENT_FNHEAT_STAGE_2 = IN_G | IN_W1 | IN_W2

    EVENT_FNHEAT_STAGE_1_ACC = IN_G | IN_W1 | IN_ACC
    EVENT_FNHEAT_STAGE_2_ACC = IN_G | IN_W1 | IN_W2 | IN_ACC

    EVENT_HPHEAT_STAGE_1 = IN_G | IN_Y1
    EVENT_HPHEAT_STAGE_1_AUX_1 = IN_G | IN_Y1 | IN_W1
    EVENT_HPHEAT_STAGE_1_AUX_2 = IN_G | IN_Y1 | IN_W1 | IN_W2

    EVENT_HPHEAT_STAGE_1_ACC = IN_G | IN_Y1
    EVENT_HPHEAT_STAGE_1_AUX_1_ACC = IN_G | IN_Y1 | IN_W1 | IN_ACC
    EVENT_HPHEAT_STAGE_1_AUX_2_ACC = IN_G | IN_Y1 | IN_W1 | IN_W2 | IN_ACC

    EVENT_HPHEAT_STAGE_2 = IN_G | IN_Y1 | IN_Y2
    EVENT_HPHEAT_STAGE_2_AUX_1 = IN_G | IN_Y1 | IN_Y2 | IN_W1
    EVENT_HPHEAT_STAGE_2_AUX_2 = IN_G | IN_Y1 | IN_Y2 | IN_W1 | IN_W2

    EVENT_HPHEAT_OB_STAGE_1 = IN_G | IN_Y1 | IN_OB
    EVENT_HPHEAT_OB_STAGE_1_AUX_1 = IN_G | IN_Y1 | IN_W1 | IN_OB
    EVENT_HPHEAT_OB_STAGE_1_AUX_2 = IN_G | IN_Y1 | IN_W1 | IN_W2 | IN_OB

    EVENT_HPHEAT_OB_STAGE_1_ACC = IN_G | IN_Y1 | IN_OB | IN_ACC
    EVENT_HPHEAT_OB_STAGE_1_AUX_1_ACC = IN_G | IN_Y1 | IN_W1 | IN_OB | IN_ACC
    EVENT_HPHEAT_OB_STAGE_1_AUX_2_ACC = IN_G | IN_Y1 | IN_W1 | IN_W2 | IN_OB | IN_ACC

    EVENT_HPHEAT_OB_STAGE_2 = IN_G | IN_Y1 | IN_Y2 | IN_OB
    EVENT_HPHEAT_OB_STAGE_2_AUX_1 = IN_G | IN_Y1 | IN_Y2 | IN_W1 | IN_OB
    EVENT_HPHEAT_OB_STAGE_2_AUX_2 = IN_G | IN_Y1 | IN_Y2 | IN_W1 | IN_W2 | IN_OB

    EVENT_HPHEAT_OB_STAGE_2_ACC = IN_G | IN_Y1 | IN_Y2 | IN_OB | IN_ACC
    EVENT_HPHEAT_OB_STAGE_2_AUX_1_ACC = IN_G | IN_Y1 | IN_Y2 | IN_W1 | IN_OB | IN_ACC
    EVENT_HPHEAT_OB_STAGE_2_AUX_2_ACC = IN_G | IN_Y1 | IN_Y2 | IN_W1 | IN_W2 | IN_OB | IN_ACC

    EVENT_AXHEAT_AUX_1 = IN_G | IN_W1
    EVENT_AXHEAT_AUX_2 = IN_G | IN_W1 | IN_W2

    EVENT_AXHEAT_AUX_1_ACC = IN_G | IN_W1 | IN_ACC
    EVENT_AXHEAT_AUX_2_ACC = IN_G | IN_W1 | IN_W2 | IN_ACC

    EVENT_AXHEAT_OB_AUX_1 = IN_G | IN_W1 | IN_OB
    EVENT_AXHEAT_OB_AUX_2 = IN_G | IN_W1 | IN_W2 | IN_OB

    EVENT_AXHEAT_OB_AUX_1_ACC = IN_G | IN_W1 | IN_OB | IN_ACC
    EVENT_AXHEAT_OB_AUX_2_ACC = IN_G | IN_W1 | IN_W2 | IN_OB | IN_ACC

    EVENT_ACCOOL_STAGE_1 = IN_G | IN_Y1
    EVENT_ACCOOL_STAGE_2 = IN_G | IN_Y1 | IN_Y2

    EVENT_ACCOOL_STAGE_1_ACC = IN_G | IN_Y1 | IN_ACC
    EVENT_ACCOOL_STAGE_2_ACC = IN_G | IN_Y1 | IN_Y2 | IN_ACC

    EVENT_HPCOOL_STAGE_1 = IN_G | IN_Y1
    EVENT_HPCOOL_OB_STAGE_1 = IN_G | IN_Y1 | IN_OB
    EVENT_HPCOOL_STAGE_2 = IN_G | IN_Y1 | IN_Y2
    EVENT_HPCOOL_OB_STAGE_2 = IN_G | IN_Y1 | IN_Y2 | IN_OB

    EVENT_HPCOOL_STAGE_1_ACC = IN_G | IN_Y1 | IN_ACC
    EVENT_HPCOOL_OB_STAGE_1_ACC = IN_G | IN_Y1 | IN_OB | IN_ACC
    EVENT_HPCOOL_STAGE_2_ACC = IN_G | IN_Y1 | IN_Y2 | IN_ACC
    EVENT_HPCOOL_OB_STAGE_2_ACC = IN_G | IN_Y1 | IN_Y2 | IN_OB | IN_ACC


# Multi-speed fan Configurations:
# Multi-speed fan ALLOWS 2-stage furnance with 2-stage fan (W+W2 AND G+G2)
# Multi-speed fan DOES NOT ALLOW 2-stage AC with 2-stage fan (Y+Y2 AND G+G3)

    # 2-speed
    EVENT_ACC_ON_FAN2 = IN_G | IN_G2 | IN_ACC
    EVENT_HP_FAN2 = IN_G | IN_G2 | IN_OB
    EVENT_HP_FAN2_ACC = IN_G | IN_G2 | IN_OB | IN_ACC

    EVENT_BOHEAT_STAGE_1_ACC_FAN2 = IN_W1 | IN_G | IN_G2 | IN_ACC
    EVENT_BOHEAT_STAGE_2_ACC_FAN2 = IN_W1 | IN_W2 | IN_G | IN_G2 | IN_ACC

    EVENT_BFHEAT_STAGE_1_FAN2 = IN_G | IN_G2 | IN_W1
    EVENT_BFHEAT_STAGE_2_FAN2 = IN_G | IN_G2 | IN_W1 | IN_W2
    EVENT_BFHEAT_STAGE_1_ACC_FAN2 = IN_G | IN_G2 | IN_W1 | IN_ACC
    EVENT_BFHEAT_STAGE_2_ACC_FAN2 = IN_G | IN_G2 | IN_W1 | IN_W2 | IN_ACC

    EVENT_FNHEAT_STAGE_1_FAN2 = IN_G | IN_G2 | IN_W1
    EVENT_FNHEAT_STAGE_2_FAN2 = IN_G | IN_G2 | IN_W1 | IN_W2
    EVENT_FNHEAT_STAGE_1_ACC_FAN2 = IN_G | IN_G2 | IN_W1 | IN_ACC
    EVENT_FNHEAT_STAGE_2_ACC_FAN2 = IN_G | IN_G2 | IN_W1 | IN_W2 | IN_ACC

    EVENT_HPHEAT_STAGE_1_FAN2 = IN_G | IN_G2 | IN_Y1
    EVENT_HPHEAT_STAGE_1_AUX_1_FAN2 = IN_G | IN_G2 | IN_Y1 | IN_W1
    EVENT_HPHEAT_STAGE_1_AUX_2_FAN2 = IN_G | IN_G2 | IN_Y1 | IN_W1 | IN_W2
    EVENT_HPHEAT_STAGE_1_ACC_FAN2 = IN_G | IN_G2 | IN_Y1
    EVENT_HPHEAT_STAGE_1_AUX_1_ACC_FAN2 = IN_G | IN_G2 | IN_Y1 | IN_W1 | IN_ACC
    EVENT_HPHEAT_STAGE_1_AUX_2_ACC_FAN2 = IN_G | IN_G2 | IN_Y1 | IN_W1 | IN_W2 | IN_ACC

    EVENT_HPHEAT_OB_STAGE_1_FAN2 = IN_G | IN_G2 | IN_Y1 | IN_OB
    EVENT_HPHEAT_OB_STAGE_1_AUX_1_FAN2 = IN_G | IN_G2 | IN_Y1 | IN_W1 | IN_OB
    EVENT_HPHEAT_OB_STAGE_1_AUX_2_FAN2 = IN_G | IN_G2 | IN_Y1 | IN_W1 | IN_W2 | IN_OB
    EVENT_HPHEAT_OB_STAGE_1_ACC_FAN2 = IN_G | IN_G2 | IN_Y1 | IN_OB | IN_ACC
    EVENT_HPHEAT_OB_STAGE_1_AUX_1_ACC_FAN2 = IN_G | IN_G2 | IN_Y1 | IN_W1 | IN_OB | IN_ACC
    EVENT_HPHEAT_OB_STAGE_1_AUX_2_ACC_FAN2 = IN_G | IN_G2 | IN_Y1 | IN_W1 | IN_W2 | IN_OB | IN_ACC

    EVENT_AXHEAT_AUX_1_FAN2 = IN_G | IN_G2 | IN_W1
    EVENT_AXHEAT_AUX_2_FAN2 = IN_G | IN_G2 | IN_W1 | IN_W2
    EVENT_AXHEAT_AUX_1_ACC_FAN2 = IN_G | IN_G2 | IN_W1 | IN_ACC
    EVENT_AXHEAT_AUX_2_ACC_FAN2 = IN_G | IN_G2 | IN_W1 | IN_W2 | IN_ACC

    EVENT_AXHEAT_OB_AUX_1_FAN2 = IN_G | IN_G2 | IN_W1 | IN_OB
    EVENT_AXHEAT_OB_AUX_2_FAN2 = IN_G | IN_G2 | IN_W1 | IN_W2 | IN_OB
    EVENT_AXHEAT_OB_AUX_1_ACC_FAN2 = IN_G | IN_G2 | IN_W1 | IN_OB | IN_ACC
    EVENT_AXHEAT_OB_AUX_2_ACC_FAN2 = IN_G | IN_G2 | IN_W1 | IN_W2 | IN_OB | IN_ACC

    EVENT_ACCOOL_STAGE_1_FAN2 = IN_G | IN_G2 | IN_Y1
    EVENT_ACCOOL_STAGE_1_ACC_FAN2 = IN_G | IN_G2 | IN_Y1 | IN_ACC

    EVENT_HPCOOL_STAGE_1_FAN2 = IN_G | IN_G2 | IN_Y1
    EVENT_HPCOOL_OB_STAGE_1_FAN2 = IN_G | IN_G2 | IN_Y1 | IN_OB
    EVENT_HPCOOL_STAGE_1_ACC_FAN2 = IN_G | IN_G2 | IN_Y1 | IN_ACC
    EVENT_HPCOOL_OB_STAGE_1_ACC_FAN2 = IN_G | IN_G2 | IN_Y1 | IN_OB | IN_ACC

    # 3-speed
    EVENT_ACC_ON_FAN3 = IN_G | IN_G2 | IN_G3 | IN_ACC
    EVENT_HP_FAN3 = IN_G | IN_G2 | IN_G3 | IN_OB
    EVENT_HP_FAN3_ACC = IN_G | IN_G2 | IN_G3 | IN_OB | IN_ACC

    EVENT_BOHEAT_STAGE_1_ACC_FAN3 = IN_W1 | IN_G | IN_G2 | IN_G3 | IN_ACC

    EVENT_BFHEAT_STAGE_1_FAN3 = IN_G | IN_G2 | IN_G3 | IN_W1
    EVENT_BFHEAT_STAGE_1_ACC_FAN3 = IN_G | IN_G2 | IN_G3 | IN_W1 | IN_ACC

    EVENT_FNHEAT_STAGE_1_FAN3 = IN_G | IN_G2 | IN_G3 | IN_W1
    EVENT_FNHEAT_STAGE_1_ACC_FAN3 = IN_G | IN_G2 | IN_G3 | IN_W1 | IN_ACC

    EVENT_HPHEAT_STAGE_1_FAN3 = IN_G | IN_G2 | IN_G3 | IN_Y1
    EVENT_HPHEAT_STAGE_1_AUX_1_FAN3 = IN_G | IN_G2 | IN_G3 | IN_Y1 | IN_W1
    EVENT_HPHEAT_STAGE_1_ACC_FAN3 = IN_G | IN_G2 | IN_G3 | IN_Y1
    EVENT_HPHEAT_STAGE_1_AUX_1_ACC_FAN3 = IN_G | IN_G2 | IN_G3 | IN_Y1 | IN_W1 | IN_ACC

    EVENT_HPHEAT_OB_STAGE_1_FAN3 = IN_G | IN_G2 | IN_G3 | IN_Y1 | IN_OB
    EVENT_HPHEAT_OB_STAGE_1_AUX_1_FAN3 = IN_G | IN_G2 | IN_G3 | IN_Y1 | IN_W1 | IN_OB
    EVENT_HPHEAT_OB_STAGE_1_ACC_FAN3 = IN_G | IN_G2 | IN_G3 | IN_Y1 | IN_OB | IN_ACC
    EVENT_HPHEAT_OB_STAGE_1_AUX_1_ACC_FAN3 = IN_G | IN_G2 | IN_G3 | IN_Y1 | IN_W1 | IN_OB | IN_ACC

    EVENT_AXHEAT_AUX_1_FAN3 = IN_G | IN_G2 | IN_G3 | IN_W1
    EVENT_AXHEAT_AUX_1_ACC_FAN3 = IN_G | IN_G2 | IN_G3 | IN_W1 | IN_ACC

    EVENT_AXHEAT_OB_AUX_1_FAN3 = IN_G | IN_G2 | IN_G3 | IN_W1 | IN_OB
    EVENT_AXHEAT_OB_AUX_1_ACC_FAN3 = IN_G | IN_G2 | IN_G3 | IN_W1 | IN_OB | IN_ACC

    EVENT_ACCOOL_STAGE_1_FAN3 = IN_G | IN_G2 | IN_G3 | IN_Y1
    EVENT_ACCOOL_STAGE_1_ACC_FAN3 = IN_G | IN_G2 | IN_G3 | IN_Y1 | IN_ACC

    EVENT_HPCOOL_STAGE_1_FAN3 = IN_G | IN_G2 | IN_G3 | IN_Y1
    EVENT_HPCOOL_OB_STAGE_1_FAN3 = IN_G | IN_G2 | IN_G3 | IN_Y1 | IN_OB
    EVENT_HPCOOL_STAGE_1_ACC_FAN3 = IN_G | IN_G2 | IN_G3 | IN_Y1 | IN_ACC
    EVENT_HPCOOL_OB_STAGE_1_ACC_FAN3 = IN_G | IN_G2 | IN_G3 | IN_Y1 | IN_OB | IN_ACC
